### ISSUE TITLE
开箱即用报错

### ISSUE THREAD

**Issue by zoooozz** [storyicon/golang-proxy#6] opened 2019-07-29 15:15 UTC
Error 1305: FUNCTION proxy.RANDOM does not exist"

**Comment by storyicon** [comment] 2019-08-05 02:52
Sorry, I am late. How can I reproduce this mistake? 
①If you're using [binary files here](https://github.com/storyicon/golang-proxy/releases)
In theory, this kind of error will not occur. Because "the function does not exist" will be thrown at compile time.
②If you compile it yourself
I just pulled the code from master branch and compiled it successfully.

I need more information.

**Comment by assoyuan** [comment] 2020-02-19 08:06
> ①If you're using [binary files here](https://github.com/storyicon/golang-proxy/releases)
> In theory, this kind of error will not occur. Because "the function does not exist" will be thrown at compile time.

Download the base file, after executing, visit "localhost: 9999 / random" in the browser and report the error:
{"error": "Error 1305: FUNCTION proxy.RANDOM does not exist", "message": []}

**Comment by storyicon** [comment] 2020-04-20 04:15
Apologize for my late arrival. I just fixed this problem.
Duplicate of #7

**Closed as completed by storyicon** 2020-04-20 04:15 UTC
Labels: question
